### PR TITLE
PR: added ability to read data file from the gateway

### PR DESCRIPTION
**Pull request by monaw**
Done for issue #8  : User upload from gateway home directory and also updated changed code in bin/

### CODE REVIEW

**Comment by sinkovit** [comment]
Thanks for adding this feature. Just make sure that this does not break ability to read from local file on the user's computer.

**Comment by monaw** [comment]
hi @sinkovit, to merge the changes from the feature branch to main, you need to click on the "Merge pull request" green button above first before closing the PR.  i've reopened the PR so you can give that another try, thanks!

**Comment by monaw** [comment]
hmm, still not merge...let me give it a try...

**Comment by monaw** [comment]
hi Bob, now the PR code is merged; not sure why it didn't work for you...did you click on the green "Confirm merge" button?

**Comment by sinkovit** [comment]
I thought I did, but I’m guessing that I didn’t. Thanks for your patience!

-- Bob

From: MonaW ***@***.***>
Reply-To: sinkovit/Spatial-ecology ***@***.***>
Date: Wednesday, January 11, 2023 at 5:56 PM
To: sinkovit/Spatial-ecology ***@***.***>
Cc: "Sinkovits, Robert" ***@***.***>, State change ***@***.***>
Subject: Re: [sinkovit/Spatial-ecology] PR: added ability to read data file from the gateway (PR #39)


hi Bob, now the PR code is merged; not sure why it didn't work for you...did you click on the green "Confirm merge" button?

**Pull request merged**
